import numpy as np
import matplotlib.pylab as plt
filename = "euler_01.dat"
x=np.loadtxt(filename, usecols=0)
y=np.loadtxt(filename, usecols=1)
w=np.loadtxt(filename, usecols=2)
plt.figure(figsize=(15,6))
plt.subplot(1,3,1)
plt.title('Y vs X')
plt.xlabel('x')
plt.ylabel('y')
plt.plot(x,y)
plt.subplot(1,3,2)
plt.title('dY/dX vs X')
plt.xlabel('x')
plt.ylabel('dy/dx')
plt.plot(x,w)
plt.subplot(1,3,3)
plt.title('dY/dX vs Y')
plt.xlabel('y')
plt.ylabel('dy/dx')
plt.plot(y,w)
plt.savefig('grafica_01.png')
plt.close()

filename = "euler_001.dat"
x=np.loadtxt(filename, usecols=0)
y=np.loadtxt(filename, usecols=1)
w=np.loadtxt(filename, usecols=2)
plt.figure(figsize=(15,6))
plt.subplot(1,3,1)
plt.title('Y vs X')
plt.xlabel('x')
plt.ylabel('y')
plt.plot(x,y,c='green')
plt.subplot(1,3,2)
plt.title('dY/dX vs X')
plt.xlabel('x')
plt.ylabel('dy/dx')
plt.plot(x,w,c='green')
plt.subplot(1,3,3)
plt.title('dY/dX vs Y')
plt.xlabel('y')
plt.ylabel('dy/dx')
plt.plot(y,w,c='green')
plt.savefig('grafica_001.png')
plt.close()

filename = "euler_1.dat"
x=np.loadtxt(filename, usecols=0)
y=np.loadtxt(filename, usecols=1)
w=np.loadtxt(filename, usecols=2)
plt.figure(figsize=(15,6))
plt.subplot(1,3,1)
plt.title('Y vs X')
plt.xlabel('x')
plt.ylabel('y')
plt.plot(x,y,c='orange')
plt.subplot(1,3,2)
plt.title('dY/dX vs X')
plt.xlabel('x')
plt.ylabel('dy/dx')
plt.plot(x,w,c='orange')
plt.subplot(1,3,3)
plt.title('dY/dX vs Y')
plt.xlabel('y')
plt.ylabel('dy/dx')
plt.plot(y,w,c='orange')
plt.savefig('grafica_1.png')